name : Ankit Patkar

on:
    push:
      branches: [ main  ]

   jobs:
      demo:
        runs-on: ubuntu-latest

        steps:
           - name: Greetings
             run: echo "Hello From Apun"
    
    
